export const industries = [
  { slug: 'turismo-y-hoteleria', title: 'Comunicación para turismo y hotelería en Córdoba, Argentina', names: ['bahia norte', 'la ribera', 'nueva generacion'], sections: [
    { title: 'Mostrar la experiencia antes de la reserva', text: 'Un alojamiento necesita presentar habitaciones, espacios comunes, ubicación y servicios con información clara. La producción de fotos y videos puede ayudar a que una persona entienda qué experiencia va a encontrar. Para camping y propuestas turísticas, también importa explicar accesos, actividades y características del lugar. Organizamos el contenido según lo que cada negocio ofrece, sin sumar instalaciones ni beneficios que no estén confirmados.' },
    { title: 'Contenidos para cada temporada', text: 'Las necesidades de comunicación cambian entre el lanzamiento de una temporada, una promoción y la presentación institucional. Podemos coordinar identidad visual, publicaciones, fotografía y producción audiovisual. Una jornada planificada permite identificar qué imágenes siguen siendo útiles durante el año y cuáles corresponden a una campaña concreta. Revisamos con el cliente precios, disponibilidad y condiciones antes de publicar información comercial.' },
    { title: 'Producción y logística', text: 'Antes de visitar el lugar, acordamos ambientes, horarios y condiciones de acceso. Conviene preparar espacios y coordinar con el equipo para evitar interferir con huéspedes o actividades. Las tomas con dron se evalúan según la viabilidad de cada locación. Trabajamos desde Villa Carlos Paz en toda la provincia de Córdoba, Argentina, con reuniones remotas y jornadas presenciales que contemplan viáticos según distancia.' },
    { title: 'Casos del rubro', text: 'Explorá los trabajos publicados de turismo y hotelería: fotografía, identidad y contenido para mostrar espacios y propuestas de temporada.' }
  ] },
  { slug: 'inmobiliarias', title: 'Fotografía y comunicación para inmobiliarias en Córdoba, Argentina', names: ['noe garcia', 'roñoni', 'rononi'], sections: [
    { title: 'Presentar propiedades con información útil', text: 'Las imágenes de una propiedad deben ayudar a entender su distribución y sus características. Planificamos fotografía inmobiliaria y arquitectónica con una secuencia de ambientes, detalles y exteriores que responda al uso previsto. Para una publicación en redes puede ser necesario un resumen; para una ficha, un conjunto más amplio. Acordamos esas necesidades antes de la sesión para organizar los entregables.' },
    { title: 'Identidad y materiales comerciales', text: 'Una inmobiliaria también necesita una identidad reconocible y piezas consistentes para presentar su propuesta. Podemos trabajar branding, diseño gráfico y contenido para redes como servicios diferenciados. Los datos de las propiedades, sus medidas, disponibilidad y condiciones deben ser aportados y confirmados por el cliente. El diseño organiza esa información y evita que cada publicación parezca pertenecer a una marca distinta.' },
    { title: 'Coordinar el acceso a cada inmueble', text: 'Para producir fotos o video necesitamos una persona responsable del acceso, ambientes preparados y una fecha coordinada. Revisamos horarios de luz y prioridades de registro. Las vistas aéreas pueden complementar el material cuando la locación y las condiciones permiten realizarlas. Coordinamos revisiones a distancia y jornadas en Villa Carlos Paz o en otras ciudades de la provincia de Córdoba, Argentina, con viáticos según distancia.' },
    { title: 'Referencia real del portfolio', text: 'Explorá el trabajo de branding, edición de video y diseño gráfico para Inmobiliaria Noe García Roñoni, con base en Villa Carlos Paz.' }
  ] },
  { slug: 'gastronomia', title: 'Diseño y contenido para gastronomía en Córdoba, Argentina', names: ['mike'], sections: [
    { title: 'Mostrar el producto y explicar la propuesta', text: 'La comunicación gastronómica combina identidad, producto e información práctica. Una foto puede presentar una preparación, mientras una pieza de diseño organiza variedades, horarios o condiciones de una promoción. Planificamos contenidos con datos confirmados para que el interés visual vaya acompañado de información que permita consultar. La disponibilidad y los precios deben revisarse con el negocio antes de publicar.' },
    { title: 'De la identidad al envase', text: 'Podemos trabajar branding, fotografía de producto, diseño gráfico y packaging según las necesidades del local o de la marca. Una línea de envases requiere definir medidas, materiales y textos antes de preparar archivos. Los menús y las publicaciones tienen otros requisitos de lectura. Organizamos cada aplicación alrededor de la identidad y distinguimos los entregables para que puedas priorizar qué desarrollar primero.' },
    { title: 'Organizar una producción gastronómica', text: 'Una sesión necesita productos preparados, tiempos de cocina coordinados y referencias claras sobre el uso de las imágenes. Si se van a producir reels, conviene identificar qué momentos del proceso interesa registrar. Acordamos la jornada para aprovechar el material sin interferir innecesariamente con la operación del local. Trabajamos desde Villa Carlos Paz para la provincia de Córdoba, Argentina; fuera de la ciudad contemplamos viáticos según distancia.' },
    { title: 'Un caso para explorar', text: 'Conocé la fotografía de producto para Mike Donas: dirección de arte gastronómica e imágenes para presentar sus productos en canales digitales.' }
  ] }
] as const;
export const locations = [
  { slug: 'villa-carlos-paz', title: 'Consultora creativa en Villa Carlos Paz, Córdoba, Argentina', sections: [
    { title: 'Nuestra base de trabajo', text: 'Quepia tiene base en Villa Carlos Paz. Acompañamos marcas con branding, diseño gráfico, gestión de redes, fotografía, producción audiovisual y packaging. La cercanía permite coordinar relevamientos y jornadas de producción cuando el proyecto los requiere. Las reuniones también pueden hacerse por videollamada para facilitar las revisiones y compartir materiales sin depender de encuentros presenciales en cada etapa.' },
    { title: 'Comunicación para una ciudad turística', text: 'En negocios de turismo y servicios, las imágenes del espacio, la claridad de la propuesta y la información actualizada tienen un papel central. Podemos organizar producciones para mostrar ambientes, productos o actividades y convertirlas en piezas para distintos canales. El contenido se construye con datos aportados por cada marca. No suponemos que todos los negocios tienen la misma estacionalidad: revisamos sus objetivos y calendario antes de proponer una planificación.' },
    { title: 'Cómo coordinamos', text: 'Primero nos contás qué necesitás y qué materiales tenés. Después definimos alcance, entregables y revisiones. Cuando una producción requiere traslado, se acuerdan las condiciones en la propuesta. Si tu equipo trabaja fuera de Carlos Paz, podemos sostener el proceso a distancia y concentrar las tareas presenciales en jornadas planificadas. Para coordinar un encuentro, consultanos previamente por los canales de contacto.' }
  ] },
  { slug: 'cordoba', title: 'Servicios creativos en Córdoba Capital y provincia de Córdoba, Argentina', sections: [
    { title: 'Coordinación provincial desde Carlos Paz', text: 'Trabajamos con marcas de Córdoba Capital y otras localidades de la provincia desde nuestra base en Villa Carlos Paz. Los proyectos de identidad, diseño y planificación de contenidos pueden desarrollarse a distancia. Para fotografía, video o cobertura con dron, coordinamos una jornada en la locación y contemplamos viáticos según distancia. La ciudad no define el estilo de una marca: el alcance se construye a partir de sus objetivos y recursos.' },
    { title: 'Producción en Córdoba Capital', text: 'Una jornada en Capital requiere organizar accesos, horarios y disponibilidad del lugar. Si hay varios espacios o productos, conviene definir prioridades y tiempos de preparación antes de grabar. Las condiciones para tomas con dron se revisan para cada locación; no se confirma una operación solamente por la ciudad. Podemos combinar material de suelo y aéreo cuando resulta pertinente y viable, con formatos previstos para los canales donde se va a publicar.' },
    { title: 'Una propuesta según el proyecto', text: 'Contanos la ciudad, el objetivo y la fecha orientativa. Podemos coordinar branding, redes, diseño, packaging y producción audiovisual como etapas diferenciadas o como un proyecto con entregables acordados. Las revisiones digitales permiten mantener un circuito claro entre equipos de distintas localidades. Si hay impresión o fabricación, necesitamos las especificaciones del proveedor para preparar archivos que respondan al soporte elegido.' }
  ] },
  { slug: 'valle-de-punilla', title: 'Diseño y producción audiovisual en el Valle de Punilla, Córdoba, Argentina', sections: [
    { title: 'Mostrar espacios y experiencias serranas', text: 'Para alojamientos, actividades turísticas y negocios del Valle de Punilla, el entorno puede ser parte importante de la propuesta. La fotografía y el video permiten mostrar tanto espacios como detalles de la experiencia. Definimos qué necesita comprender el visitante y qué recursos conviene producir para explicarlo. Las tomas aéreas se evalúan cuando aportan contexto y las condiciones de la locación permiten realizarlas.' },
    { title: 'Logística entre localidades', text: 'Las distancias, los accesos y la luz disponible influyen en una jornada de producción. Antes de confirmar una fecha necesitamos conocer el lugar y las actividades previstas. Acordamos viáticos según distancia desde Villa Carlos Paz y organizamos los horarios para aprovechar el registro. Si el clima afecta una producción exterior o un vuelo, las alternativas se conversan de acuerdo con las condiciones del proyecto.' },
    { title: 'Continuidad después de la producción', text: 'Los materiales pueden acompañar redes sociales, piezas de diseño y presentaciones de marca. La planificación y la revisión se coordinan por videollamada para que el proceso siga avanzando sin trasladarnos en cada etapa. Si tu identidad necesita una actualización o querés ordenar un conjunto de piezas, definimos ese alcance por separado. Contanos en qué localidad estás y qué querés comunicar para preparar una propuesta concreta.' }
  ] }
] as const;
export function normalizedName(value: string) { return value.normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLowerCase(); }
