-- PROPUESTA PARA REVISIÓN. NO APLICADA.
-- Lectura de origen: portfolio público, 2026-10-05.
-- Actualizaciones con condición del texto anterior para no pisar ediciones posteriores.
BEGIN;
UPDATE public.proyectos SET descripcion = 'Producción fotográfica de retrato y producto para Onix, enfocada en textura, iluminación controlada y piezas listas para catálogo y redes sociales.' WHERE id = '568dcd4e-f6c6-43e8-b4bd-9b70d4a39095' AND descripcion IS NOT DISTINCT FROM 'Produccion fotografica de retrato y producto para Onix, enfocada en textura, iluminacion controlada y piezas listas para catalogo y redes sociales.';
UPDATE public.proyectos SET descripcion = 'Sesión de fotografía de producto para Mike Donas con dirección de arte gastronómica y versiones optimizadas para e-commerce, piezas promocionales y redes.' WHERE id = 'ae2a64c7-368b-4330-8520-c8131bffd0cb' AND descripcion IS NOT DISTINCT FROM 'Sesion de fotografia de producto para Mike Donas con direccion de arte gastronomica y versiones optimizadas para e-commerce, piezas promocionales y redes.';
UPDATE public.proyectos SET titulo = 'Fotografía Inmobiliaria' WHERE id = '32539811-92e7-45b1-a865-2f1f00e9b405' AND titulo IS NOT DISTINCT FROM 'Fotografia Inmobiliaria';
UPDATE public.proyectos SET descripcion = 'Cobertura fotográfica de propiedades residenciales y comerciales orientada a venta y alquiler, priorizando amplitud, luz natural y lectura espacial.' WHERE id = '32539811-92e7-45b1-a865-2f1f00e9b405' AND descripcion IS NOT DISTINCT FROM 'Cobertura fotografica de propiedades residenciales y comerciales orientada a venta y alquiler, priorizando amplitud, luz natural y lectura espacial.';
UPDATE public.proyectos SET titulo = 'Fotografía Arquitectónica' WHERE id = 'e8603d93-8ed0-417a-ae46-a46412bb99f5' AND titulo IS NOT DISTINCT FROM 'Fotografia Arquitectonica';
UPDATE public.proyectos SET descripcion = 'Registro fotográfico arquitectónico de exteriores e interiores con composición limpia, control de líneas y corrección de perspectiva para comunicación profesional.' WHERE id = 'e8603d93-8ed0-417a-ae46-a46412bb99f5' AND descripcion IS NOT DISTINCT FROM 'Registro fotografico arquitectonico de exteriores e interiores con composicion limpia, control de lineas y correccion de perspectiva para comunicacion profesional.';
UPDATE public.proyectos SET titulo = 'Modelo Histórico AILE 2023' WHERE id = '4933b717-5046-44c3-a64f-9f4f532e10d1' AND titulo IS NOT DISTINCT FROM 'Modelo Historico AILE 2023';
UPDATE public.proyectos SET descripcion = 'Desarrollo gráfico del modelo histórico AILE 2023 para comunicar evolución institucional en presentaciones, documentos editoriales y difusión digital.' WHERE id = '4933b717-5046-44c3-a64f-9f4f532e10d1' AND descripcion IS NOT DISTINCT FROM 'Desarrollo grafico del modelo historico AILE 2023 para comunicar evolucion institucional en presentaciones, documentos editoriales y difusion digital.';
UPDATE public.proyectos SET titulo = 'Asunción - Pablo Cornet' WHERE id = '1a7dce7c-a7ea-42bc-9bf6-d9e85d1e4c3d' AND titulo IS NOT DISTINCT FROM 'Asuncion - Pablo Cornet';
UPDATE public.proyectos SET descripcion = 'Serie fotográfica documental realizada en Asunción para Pablo Cornet, combinando retrato contextual, arquitectura urbana y narrativa visual de territorio.' WHERE id = '1a7dce7c-a7ea-42bc-9bf6-d9e85d1e4c3d' AND descripcion IS NOT DISTINCT FROM 'Serie fotografica documental realizada en Asuncion para Pablo Cornet, combinando retrato contextual, arquitectura urbana y narrativa visual de territorio.';
UPDATE public.proyectos SET descripcion = 'Diseño de logotipo e identidad base para INDAR, marca de ropa de trabajo, con sistema de aplicaciones para indumentaria, etiquetas y piezas corporativas.' WHERE id = '44937837-2aaf-41c7-8a68-2ce6dc5ea832' AND descripcion IS NOT DISTINCT FROM 'Diseno de logotipo e identidad base para INDAR, marca de ropa de trabajo, con sistema de aplicaciones para indumentaria, etiquetas y piezas corporativas.';
UPDATE public.proyectos SET descripcion = 'Creación de identidad visual para Dalton Indumentaria, definiendo estructura tipográfica, variantes de marca y reglas de uso para soportes físicos y digitales.' WHERE id = 'dca1cd7f-08f8-490a-aff3-adeb337c0d8d' AND descripcion IS NOT DISTINCT FROM 'Creacion de identidad visual para Dalton Indumentaria, definiendo estructura tipografica, variantes de marca y reglas de uso para soportes fisicos y digitales.';
UPDATE public.proyectos SET descripcion = 'Sistema de identidad visual para CEL: construcción de logo, paleta cromática, lineamientos de marca y piezas institucionales de uso cotidiano.' WHERE id = '143b1c6f-9d87-4464-89af-637d32c4b64b' AND descripcion IS NOT DISTINCT FROM 'Sistema de identidad visual para CEL: construccion de logo, paleta cromatica, lineamientos de marca y piezas institucionales de uso cotidiano.';
UPDATE public.proyectos SET titulo = 'Hotel Bahía Norte - Social Media' WHERE id = '6aea1c25-87db-4cc6-be7c-896f9df366c5' AND titulo IS NOT DISTINCT FROM 'Hotel Bahia Norte - Social Media';
UPDATE public.proyectos SET descripcion = 'Producción de piezas y línea visual para redes de Hotel Bahía Norte, integrando contenido fotográfico, diseño gráfico y mensajes promocionales de temporada.' WHERE id = '6aea1c25-87db-4cc6-be7c-896f9df366c5' AND descripcion IS NOT DISTINCT FROM 'Produccion de piezas y linea visual para redes de Hotel Bahia Norte, integrando contenido fotografico, diseno grafico y mensajes promocionales de temporada.';
UPDATE public.proyectos SET titulo = 'Rediseño AILE - Asociación' WHERE id = '5d57584a-f8a1-49be-8a25-97e1080296e9' AND titulo IS NOT DISTINCT FROM 'Rediseño AILE - Asociacion';
UPDATE public.proyectos SET descripcion = 'Proyecto de rediseño de identidad para AILE, actualizando lenguaje visual, jerarquía de marca y coherencia entre comunicación institucional y digital.' WHERE id = '5d57584a-f8a1-49be-8a25-97e1080296e9' AND descripcion IS NOT DISTINCT FROM 'Proyecto de rediseño de identidad para AILE, actualizando lenguaje visual, jerarquia de marca y coherencia entre comunicacion institucional y digital.';
UPDATE public.proyectos SET titulo = 'Identidad Visual Jóvenes PRO' WHERE id = '98b58b47-f3bf-4380-ba0e-738cc751beba' AND titulo IS NOT DISTINCT FROM 'Identidad Visual Jovenes PRO';
UPDATE public.proyectos SET descripcion = 'Desarrollo de identidad visual para Jóvenes PRO con piezas de campaña, criterios de uso en redes y material de comunicación territorial.' WHERE id = '98b58b47-f3bf-4380-ba0e-738cc751beba' AND descripcion IS NOT DISTINCT FROM 'Desarrollo de identidad visual para Jovenes PRO con piezas de campana, criterios de uso en redes y material de comunicacion territorial.';
UPDATE public.proyectos SET titulo = 'Logo Asociación de Jubilados y Pensionados' WHERE id = '11a7b09b-95d3-4dc7-a2c4-db058140c481' AND titulo IS NOT DISTINCT FROM 'Logo Asociacion de Jubilados y Pensionados';
UPDATE public.proyectos SET descripcion = 'Diseño de logotipo institucional para asociación de jubilados y pensionados, priorizando legibilidad, cercanía visual y aplicación versátil.' WHERE id = '11a7b09b-95d3-4dc7-a2c4-db058140c481' AND descripcion IS NOT DISTINCT FROM 'Diseno de logotipo institucional para asociacion de jubilados y pensionados, priorizando legibilidad, cercania visual y aplicacion versatil.';
UPDATE public.proyectos SET descripcion = 'Vectorización de logotipo y diseño de carpetas institucionales para Aristos, preparado para impresión profesional y presentaciones comerciales.' WHERE id = '170f9f5c-91be-4184-acbb-3c468b193bae' AND descripcion IS NOT DISTINCT FROM 'Vectorizacion de logotipo y diseno de carpetas institucionales para Aristos, preparado para impresion profesional y presentaciones comerciales.';
-- Revisar cambios antes de confirmar la transacción.
ROLLBACK; -- Cambiar por COMMIT únicamente al aprobar y ejecutar.
