create table if not exists public.sistema_creative_prompt_versions (
  id uuid primary key default gen_random_uuid(),
  task_id uuid not null references public.sistema_tasks(id) on delete cascade,
  project_id uuid not null references public.sistema_projects(id) on delete cascade,
  created_by uuid not null references auth.users(id) on delete restrict,
  version_number integer not null check (version_number > 0),
  piece_context jsonb not null default '{}'::jsonb,
  directions jsonb not null default '[]'::jsonb,
  selected_direction jsonb,
  prompt_pack jsonb not null default '{}'::jsonb,
  review jsonb,
  source_asset_ids uuid[] not null default '{}',
  created_at timestamptz not null default now(),
  unique (task_id, version_number)
);

create index if not exists idx_creative_prompt_versions_task_created
  on public.sistema_creative_prompt_versions (task_id, created_at desc);

create index if not exists idx_creative_prompt_versions_project
  on public.sistema_creative_prompt_versions (project_id);

alter table public.sistema_creative_prompt_versions enable row level security;

revoke all on table public.sistema_creative_prompt_versions from anon;
grant select, insert on table public.sistema_creative_prompt_versions to authenticated;
grant select, insert, update, delete on table public.sistema_creative_prompt_versions to service_role;

create policy "Project members can view creative prompt versions"
  on public.sistema_creative_prompt_versions
  for select
  to authenticated
  using (
    exists (
      select 1
      from public.sistema_tasks task
      join public.sistema_projects project on project.id = task.project_id
      where task.id = sistema_creative_prompt_versions.task_id
        and task.project_id = sistema_creative_prompt_versions.project_id
        and (
          project.owner_id = (select auth.uid())
          or exists (
            select 1
            from public.sistema_project_members member
            where member.project_id = project.id
              and member.user_id = (select auth.uid())
          )
        )
    )
  );

create policy "Project members can create creative prompt versions"
  on public.sistema_creative_prompt_versions
  for insert
  to authenticated
  with check (
    created_by = (select auth.uid())
    and exists (
      select 1
      from public.sistema_tasks task
      join public.sistema_projects project on project.id = task.project_id
      where task.id = sistema_creative_prompt_versions.task_id
        and task.project_id = sistema_creative_prompt_versions.project_id
        and (
          project.owner_id = (select auth.uid())
          or exists (
            select 1
            from public.sistema_project_members member
            where member.project_id = project.id
              and member.user_id = (select auth.uid())
              and member.role in ('owner', 'admin', 'member')
          )
        )
    )
  );

comment on table public.sistema_creative_prompt_versions is
  'Append-only prompt packs generated by the task-level Creative AI Studio.';
